"""
Employee Join Portal
Serves a web page at /join where employees can:
1. Enter their join code (generated by admin)
2. Download a pre-configured agent installer
3. See setup instructions with no CLI required

This completely removes the need for employees to edit any config files.
"""

import re
import uuid
import zipfile
import io
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.db.session import get_db
from app.models import Employee, Device, DeviceStatus
from app.core.security import generate_device_token, generate_enrollment_code, generate_one_time_token
from app.api.v1.routes.auth import require_admin_write
from app.core.logging import get_logger
from app.core.config import settings
from app.core.files import sanitize_filename_component
from app.core.rate_limit import enforce_rate_limit
from app.core.audit import log_admin_action
from app.services.token_store import token_store

router = APIRouter(tags=["join-portal"])
log = get_logger("join_portal")

JOIN_CODE_KIND = "join_portal_code"
JOIN_DOWNLOAD_KIND = "join_portal_download"
JOIN_CODE_RE = re.compile(r"^[A-Z0-9]{6}$")


def _normalize_server_url(server_url: str) -> str:
    candidate = (server_url or "").strip().rstrip("/")
    parsed = urlparse(candidate)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise HTTPException(status_code=400, detail="server_url must be a valid absolute http(s) URL")
    return candidate


# ─── Admin: generate join code ───────────────────────────────────────────────

@router.post("/api/v1/enroll/generate-join-link")
async def generate_join_link(
    request: Request,
    employee_id: uuid.UUID,
    server_url: str | None = None,
    admin=Depends(require_admin_write),
    db: AsyncSession = Depends(get_db),
):
    enforce_rate_limit(
        request,
        key_prefix="join_code_generate",
        limit=settings.ENROLLMENT_RATE_LIMIT_PER_MINUTE,
        window_seconds=60,
        include_auth_fingerprint=True,
    )

    result = await db.execute(
        select(Employee).where(Employee.id == employee_id, Employee.is_active)
    )
    employee = result.scalar_one_or_none()
    if not employee:
        raise HTTPException(status_code=404, detail="Employee not found")

    code = generate_enrollment_code()
    resolved_server_url = _normalize_server_url(server_url or str(request.base_url))
    token_store.issue(
        kind=JOIN_CODE_KIND,
        token=code,
        payload={
            "employee_id": str(employee_id),
            "employee_email": employee.email,
            "employee_name": employee.full_name,
            "server_url": resolved_server_url,
        },
        ttl_seconds=settings.JOIN_CODE_TTL_HOURS * 3600,
    )

    join_url = f"{resolved_server_url}/join"
    log.info("join_code_generated", employee=employee.email, code_hint=code[:3])
    log_admin_action(
        "join_code_generated",
        admin_id=str(admin.id),
        employee_id=str(employee_id),
    )

    return {
        "code": code,
        "join_url": join_url,
        "employee_name": employee.full_name,
        "employee_email": employee.email,
        "expires_in_hours": settings.JOIN_CODE_TTL_HOURS,
        "instructions": f"Tell {employee.full_name} to visit {join_url} and enter code: {code}",
    }


# ─── Employee: join portal web page ──────────────────────────────────────────

@router.get("/join", response_class=HTMLResponse)
async def join_portal_page():
    """The web page employees visit. No auth required."""
    return HTMLResponse(content=_render_join_page())


@router.post("/join/verify")
async def verify_join_code(request: Request, db: AsyncSession = Depends(get_db)):
    """Employee submits their join code. Returns download info."""
    enforce_rate_limit(
        request,
        key_prefix="join_verify",
        limit=settings.JOIN_VERIFY_RATE_LIMIT_PER_MINUTE,
        window_seconds=60,
    )

    body = await request.json()
    code = body.get("code", "").upper().strip()

    if not JOIN_CODE_RE.match(code):
        raise HTTPException(status_code=400, detail="Join code format is invalid.")

    rec = token_store.get(kind=JOIN_CODE_KIND, token=code)
    if not rec:
        used = token_store.get(kind=JOIN_CODE_KIND, token=code, allow_consumed=True)
        if used and used.is_consumed:
            raise HTTPException(status_code=410, detail="Join code already used. Ask your admin for a new code.")
        raise HTTPException(status_code=404, detail="Invalid or expired join code. Ask your admin for a new one.")

    payload = rec.payload
    device_id = payload.get("device_id")
    device_token = payload.get("device_token")

    if not device_id or not device_token:
        employee_id = uuid.UUID(payload["employee_id"])
        generated_device_id = uuid.uuid4()
        generated_device_token = generate_device_token(str(generated_device_id), str(employee_id))

        device = Device(
            id=generated_device_id,
            employee_id=employee_id,
            hostname="pending",
            platform="unknown",
            device_token=generated_device_token,
            status=DeviceStatus.approved,
            enrolled_at=datetime.now(timezone.utc),
        )
        db.add(device)
        await db.commit()

        device_id = str(generated_device_id)
        device_token = generated_device_token
        token_store.update_payload(
            kind=JOIN_CODE_KIND,
            token=code,
            updates={"device_id": device_id, "device_token": device_token},
        )

    download_token = generate_one_time_token(20)
    token_store.issue(
        kind=JOIN_DOWNLOAD_KIND,
        token=download_token,
        payload={"join_code": code},
        ttl_seconds=settings.JOIN_DOWNLOAD_TOKEN_TTL_MINUTES * 60,
    )

    log.info("join_code_verified", employee=payload["employee_email"], device_id=device_id)

    return {
        "employee_name": payload["employee_name"],
        "employee_email": payload["employee_email"],
        "server_url": payload["server_url"],
        "device_id": str(device_id),
        "download_url": f"/join/download/{download_token}",
    }


@router.get("/join/download/{download_token}")
async def download_agent(download_token: str, request: Request):
    """
    Downloads a ZIP containing the agent pre-configured for this employee.
    Employee just extracts and runs start.bat (Windows) or start.sh (Mac/Linux).
    """
    enforce_rate_limit(
        request,
        key_prefix="join_download",
        limit=settings.JOIN_DOWNLOAD_RATE_LIMIT_PER_MINUTE,
        window_seconds=60,
    )

    download_rec = token_store.get(kind=JOIN_DOWNLOAD_KIND, token=download_token)
    if not download_rec:
        used = token_store.get(kind=JOIN_DOWNLOAD_KIND, token=download_token, allow_consumed=True)
        if used and used.is_consumed:
            raise HTTPException(status_code=410, detail="Download link already used")
        raise HTTPException(status_code=404, detail="Invalid or expired download link")
    if not token_store.consume(kind=JOIN_DOWNLOAD_KIND, token=download_token):
        raise HTTPException(status_code=410, detail="Download link already used")

    join_code = str(download_rec.payload.get("join_code", "")).upper()
    join_rec = token_store.get(kind=JOIN_CODE_KIND, token=join_code)
    if not join_rec:
        raise HTTPException(status_code=404, detail="Enrollment code is invalid or expired")
    if not token_store.consume(kind=JOIN_CODE_KIND, token=join_code):
        raise HTTPException(status_code=410, detail="Enrollment code already used")
    info = join_rec.payload
    if not info.get("device_token") or not info.get("device_id"):
        raise HTTPException(status_code=400, detail="Enrollment is incomplete. Verify code again.")

    # Build the .env content
    env_content = f"""SERVER_URL={info['server_url']}
EMPLOYEE_EMAIL={info['employee_email']}
SAMPLE_INTERVAL_SECONDS=30
BATCH_INTERVAL_SECONDS=30
HEARTBEAT_INTERVAL_SECONDS=60
IDLE_THRESHOLD_SECONDS=300
SCREENSHOT_ENABLED=false
OFFLINE_DB_PATH=./pulsedesk_queue.db
LOG_LEVEL=INFO
DEVICE_TOKEN={info['device_token']}
DEVICE_ID={info['device_id']}
"""

    windows_bat = f"""@echo off
title PulseDesk Monitor
echo Starting PulseDesk monitoring agent...
echo Employee: {info['employee_email']}
echo.
python agent.py
pause
"""

    mac_sh = f"""#!/bin/bash
echo "Starting PulseDesk monitoring agent..."
echo "Employee: {info['employee_email']}"
python3 agent.py
"""

    readme = f"""PulseDesk Monitoring Agent
==========================
Employee : {info['employee_name']}
Email    : {info['employee_email']}
Server   : {info['server_url']}

WINDOWS SETUP:
1. Install Python 3.11 from https://www.python.org/downloads/
   (Check "Add Python to PATH" during install)
2. Open this folder
3. Double-click: install_windows.bat
4. After install, the agent starts automatically
5. The agent will auto-start on every Windows login

MAC/LINUX SETUP:
1. Make sure Python 3.9+ is installed
2. Open Terminal in this folder
3. Run: bash install_mac.sh
4. Then: bash start_mac.sh

The agent runs silently in the background and monitors:
- Which applications you use
- Keyboard and mouse activity (counts only, no content)
- Idle time
- Active window titles

All data is sent securely to your company's PulseDesk server.
"""

    install_windows = """@echo off
echo Installing PulseDesk dependencies...
setlocal
set "ROOT=%~dp0"
cd /d "%ROOT%"

where python >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] Python is not on PATH. Install Python and retry.
    pause
    exit /b 1
)

python -m pip install --upgrade pip --quiet
pip install -r requirements.txt
if %errorlevel% neq 0 (
    echo [ERROR] Dependency install failed.
    pause
    exit /b 1
)

set "STARTUP_DIR=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
if not exist "%STARTUP_DIR%" mkdir "%STARTUP_DIR%" >nul 2>&1
set "VBS_FILE=%STARTUP_DIR%\\PulseDeskAgentAutostart.vbs"
set "START_SCRIPT=%ROOT%start_windows.bat"

(
echo Set WshShell = CreateObject("WScript.Shell"^)
echo WshShell.Run Chr(34^) ^& "%START_SCRIPT%" ^& Chr(34^), 0, False
echo Set WshShell = Nothing
) > "%VBS_FILE%"

echo [OK] Auto-start configured for next login.
echo Starting agent now...
start "" /min "%START_SCRIPT%"
echo.
echo Installation complete.
echo The agent is now running and will start automatically on login.
pause
"""

    install_mac = """#!/bin/bash
echo "Installing PulseDesk dependencies..."
pip3 install -r requirements.txt
echo "Installation complete! Run: bash start_mac.sh"
"""

    # Create ZIP in memory
    agent_dir = Path(__file__).parent.parent.parent.parent.parent.parent / "agent"
    required_agent_files = [
        "agent.py",
        "requirements.txt",
        "core/config.py",
        "capture/window_tracker.py",
        "capture/input_monitor.py",
        "sync/queue.py",
        "sync/client.py",
    ]
    missing_required = [p for p in required_agent_files if not (agent_dir / p).exists()]
    if missing_required:
        log.error("join_package_missing_files", missing=missing_required)
        raise HTTPException(
            status_code=500,
            detail=f"Agent package is incomplete. Missing files: {', '.join(missing_required)}",
        )

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("pulsedesk-agent/.env", env_content)
        zf.writestr("pulsedesk-agent/README.txt", readme)
        zf.writestr("pulsedesk-agent/start_windows.bat", windows_bat)
        zf.writestr("pulsedesk-agent/start_mac.sh", mac_sh)
        zf.writestr("pulsedesk-agent/install_windows.bat", install_windows)
        zf.writestr("pulsedesk-agent/install_mac.sh", install_mac)

        # Include core agent files
        for rel_path in required_agent_files:
            full_path = agent_dir / rel_path
            if full_path.exists():
                zf.write(full_path, f"pulsedesk-agent/{rel_path}")

    zip_buffer.seek(0)
    safe_name = sanitize_filename_component(str(info["employee_name"]).replace(" ", "_"))
    filename = f"pulsedesk-agent-{safe_name}.zip"

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ─── Join page HTML ───────────────────────────────────────────────────────────

def _render_join_page() -> str:
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PulseDesk — Join</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #f5f5f4; min-height: 100vh;
    display: flex; align-items: center; justify-content: center; padding: 24px;
  }
  .card {
    background: #fff; border-radius: 16px; padding: 40px;
    box-shadow: 0 2px 12px rgba(0,0,0,0.08); width: 100%; max-width: 440px;
  }
  .logo { display: flex; align-items: center; gap: 10px; margin-bottom: 32px; justify-content: center; }
  .logo-icon {
    width: 36px; height: 36px; background: #2563eb; border-radius: 10px;
    display: flex; align-items: center; justify-content: center; color: #fff; font-size: 18px;
  }
  .logo-text { font-size: 20px; font-weight: 700; color: #1a1a18; letter-spacing: -0.02em; }
  h1 { font-size: 22px; font-weight: 600; color: #1a1a18; margin-bottom: 6px; }
  p { font-size: 14px; color: #72726a; line-height: 1.5; margin-bottom: 28px; }
  label { font-size: 12px; font-weight: 500; color: #52524e; display: block; margin-bottom: 6px; }
  input {
    width: 100%; padding: 12px 14px; font-size: 24px; font-weight: 600;
    letter-spacing: 0.2em; text-align: center; text-transform: uppercase;
    border: 1.5px solid #d1d0c8; border-radius: 10px; outline: none;
    transition: border-color 0.15s; font-family: monospace;
    color: #1a1a18; background: #fafaf9;
  }
  input:focus { border-color: #2563eb; background: #fff; }
  input::placeholder { color: #c8c7bf; letter-spacing: 0.1em; font-size: 20px; }
  .btn {
    width: 100%; padding: 14px; font-size: 15px; font-weight: 600;
    background: #2563eb; color: #fff; border: none; border-radius: 10px;
    cursor: pointer; margin-top: 16px; transition: background 0.15s;
  }
  .btn:hover { background: #1d4ed8; }
  .btn:disabled { opacity: 0.6; cursor: not-allowed; }
  .error {
    background: #fef2f2; color: #dc2626; padding: 10px 14px;
    border-radius: 8px; font-size: 13px; margin-top: 12px;
  }
  .success { display: none; }
  .success.visible { display: block; }
  .success-card {
    background: #f0fdf4; border: 1.5px solid #16a34a;
    border-radius: 12px; padding: 24px; text-align: center; margin-top: 16px;
  }
  .success-name { font-size: 18px; font-weight: 600; color: #15803d; margin-bottom: 4px; }
  .success-sub { font-size: 13px; color: #166534; margin-bottom: 20px; }
  .download-btn {
    display: inline-flex; align-items: center; gap: 8px;
    background: #16a34a; color: #fff; padding: 12px 24px;
    border-radius: 10px; font-size: 14px; font-weight: 600;
    text-decoration: none; transition: background 0.15s;
  }
  .download-btn:hover { background: #15803d; }
  .steps { margin-top: 24px; text-align: left; }
  .step { display: flex; gap: 12px; margin-bottom: 12px; align-items: flex-start; }
  .step-num {
    width: 24px; height: 24px; background: #eff6ff; color: #1d4ed8;
    border-radius: 50%; display: flex; align-items: center; justify-content: center;
    font-size: 12px; font-weight: 600; flex-shrink: 0; margin-top: 1px;
  }
  .step-text { font-size: 13px; color: #374151; line-height: 1.5; }
  .step-text strong { color: #111827; }
  .footer { text-align: center; margin-top: 24px; font-size: 12px; color: #a8a8a0; }
</style>
</head>
<body>
<div class="card">
  <div class="logo">
    <div class="logo-icon">⚡</div>
    <div class="logo-text">PulseDesk</div>
  </div>

  <div id="step1">
    <h1>Join your team</h1>
    <p>Enter the 6-character code your IT administrator sent you to set up monitoring on this device.</p>

    <label for="code">Your join code</label>
    <input type="text" id="code" maxlength="6" placeholder="ABC123"
      oninput="this.value = this.value.toUpperCase().replace(/[^A-Z0-9]/g,'')"
      onkeydown="if(event.key==='Enter') verify()">

    <div id="error" class="error" style="display:none"></div>

    <button class="btn" id="verifyBtn" onclick="verify()">
      Continue →
    </button>
  </div>

  <div id="step2" class="success">
    <div class="success-card">
      <div style="font-size:32px;margin-bottom:8px">✓</div>
      <div class="success-name" id="empName"></div>
      <div class="success-sub">Your device is enrolled and approved.</div>
      <a id="downloadBtn" class="download-btn" href="#">
        ⬇ Download monitoring agent
      </a>
    </div>

    <div class="steps">
      <div class="step">
        <div class="step-num">1</div>
        <div class="step-text"><strong>Download</strong> the ZIP file above</div>
      </div>
      <div class="step">
        <div class="step-num">2</div>
        <div class="step-text"><strong>Extract</strong> the ZIP to any folder (e.g. Desktop)</div>
      </div>
      <div class="step">
        <div class="step-num">3</div>
        <div class="step-text">
          <strong>Windows:</strong> Double-click <code>install_windows.bat</code> once (starts now + auto-start on login)<br>
          <strong>Mac:</strong> Open Terminal, run <code>bash install_mac.sh</code> then <code>bash start_mac.sh</code>
        </div>
      </div>
      <div class="step">
        <div class="step-num">4</div>
        <div class="step-text"><strong>Done!</strong> Monitoring will start automatically. Your admin can see you're online.</div>
      </div>
    </div>
  </div>

  <div class="footer">PulseDesk Employee Monitoring System</div>
</div>

<script>
async function verify() {
  const code = document.getElementById('code').value.trim();
  const btn = document.getElementById('verifyBtn');
  const errEl = document.getElementById('error');

  if (code.length < 6) {
    showError('Please enter the full 6-character code.');
    return;
  }

  btn.disabled = true;
  btn.textContent = 'Verifying...';
  errEl.style.display = 'none';

  try {
    const resp = await fetch('/join/verify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code }),
    });

    const data = await resp.json();

    if (!resp.ok) {
      showError(data.detail || 'Invalid code. Please check and try again.');
      btn.disabled = false;
      btn.textContent = 'Continue →';
      return;
    }

    // Show success
    document.getElementById('step1').style.display = 'none';
    document.getElementById('empName').textContent = 'Welcome, ' + data.employee_name + '!';
    document.getElementById('downloadBtn').href = data.download_url;
    document.getElementById('step2').classList.add('visible');

  } catch (e) {
    showError('Connection failed. Make sure the server is running.');
    btn.disabled = false;
    btn.textContent = 'Continue →';
  }
}

function showError(msg) {
  const el = document.getElementById('error');
  el.textContent = msg;
  el.style.display = 'block';
}
</script>
</body>
</html>"""
