"""
Employee Join Portal
Serves a web page at /join where employees can:
1. Enter their join code (generated by admin)
2. Download a pre-configured agent installer
3. See setup instructions with no CLI required

This completely removes the need for employees to edit any config files.
"""

import uuid
import os
import zipfile
import io
import secrets
from datetime import datetime, timezone, timedelta
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse, StreamingResponse, JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.db.session import get_db
from app.models import Employee, Device, DeviceStatus
from app.core.security import generate_device_token
from app.api.v1.routes.auth import get_current_admin
from app.core.logging import get_logger

router = APIRouter(tags=["join-portal"])
log = get_logger("join_portal")

# In-memory token store {token: {employee_id, email, name, server_url, expires_at}}
_join_tokens: dict = {}


# ─── Admin: generate join code ───────────────────────────────────────────────

@router.post("/enroll/generate-link")
async def generate_join_link(
    employee_id: uuid.UUID,
    server_url: str = "http://localhost:8000",
    admin=Depends(get_current_admin),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Employee).where(Employee.id == employee_id, Employee.is_active == True)
    )
    employee = result.scalar_one_or_none()
    if not employee:
        raise HTTPException(status_code=404, detail="Employee not found")

    # Short human-readable code like "K7X2P9"
    code = secrets.token_hex(3).upper()
    _join_tokens[code] = {
        "employee_id": str(employee_id),
        "employee_email": employee.email,
        "employee_name": employee.full_name,
        "server_url": server_url.rstrip("/"),
        "expires_at": (datetime.now(timezone.utc) + timedelta(hours=48)).isoformat(),
    }

    join_url = f"{server_url.rstrip('/')}/join"
    log.info("join_code_generated", employee=employee.email, code=code)

    return {
        "code": code,
        "join_url": join_url,
        "employee_name": employee.full_name,
        "employee_email": employee.email,
        "expires_in_hours": 48,
        "instructions": f"Tell {employee.full_name} to visit {join_url} and enter code: {code}",
    }


# ─── Employee: join portal web page ──────────────────────────────────────────

@router.get("/join", response_class=HTMLResponse)
async def join_portal_page():
    """The web page employees visit. No auth required."""
    return HTMLResponse(content=_render_join_page())


@router.post("/join/verify")
async def verify_join_code(request: Request, db: AsyncSession = Depends(get_db)):
    """Employee submits their join code. Returns download info."""
    body = await request.json()
    code = body.get("code", "").upper().strip()

    if code not in _join_tokens:
        raise HTTPException(status_code=404, detail="Invalid or expired join code. Ask your admin for a new one.")

    info = _join_tokens[code]
    expires = datetime.fromisoformat(info["expires_at"])
    if datetime.now(timezone.utc) > expires:
        del _join_tokens[code]
        raise HTTPException(status_code=410, detail="Join code expired. Ask your admin for a new one.")

    # Pre-create and approve the device
    employee_id = uuid.UUID(info["employee_id"])
    device_id = uuid.uuid4()
    device_token = generate_device_token(str(device_id), str(employee_id))

    device = Device(
        id=device_id,
        employee_id=employee_id,
        hostname="pending",
        platform="unknown",
        device_token=device_token,
        status=DeviceStatus.approved,
        enrolled_at=datetime.now(timezone.utc),
    )
    db.add(device)
    await db.commit()

    # Keep token for download (don't delete yet — employee needs to download)
    _join_tokens[code]["device_token"] = device_token
    _join_tokens[code]["device_id"] = str(device_id)

    log.info("join_code_verified", employee=info["employee_email"], device_id=str(device_id))

    return {
        "employee_name": info["employee_name"],
        "employee_email": info["employee_email"],
        "server_url": info["server_url"],
        "device_token": device_token,
        "device_id": str(device_id),
        "download_url": f"/join/download/{code}",
    }


@router.get("/join/download/{code}")
async def download_agent(code: str):
    """
    Downloads a ZIP containing the agent pre-configured for this employee.
    Employee just extracts and runs start.bat (Windows) or start.sh (Mac/Linux).
    """
    code = code.upper()
    if code not in _join_tokens or "device_token" not in _join_tokens[code]:
        raise HTTPException(status_code=404, detail="Invalid download link")

    info = _join_tokens[code]
    # Consume token after download
    del _join_tokens[code]

    # Build the .env content
    env_content = f"""SERVER_URL={info['server_url']}
EMPLOYEE_EMAIL={info['employee_email']}
SAMPLE_INTERVAL_SECONDS=30
BATCH_INTERVAL_SECONDS=30
HEARTBEAT_INTERVAL_SECONDS=60
IDLE_THRESHOLD_SECONDS=300
SCREENSHOT_ENABLED=false
OFFLINE_DB_PATH=./pulsedesk_queue.db
LOG_LEVEL=INFO
DEVICE_TOKEN={info['device_token']}
DEVICE_ID={info['device_id']}
"""

    windows_bat = f"""@echo off
title PulseDesk Monitor
echo Starting PulseDesk monitoring agent...
echo Employee: {info['employee_email']}
echo.
python agent.py
pause
"""

    mac_sh = f"""#!/bin/bash
echo "Starting PulseDesk monitoring agent..."
echo "Employee: {info['employee_email']}"
python3 agent.py
"""

    readme = f"""PulseDesk Monitoring Agent
==========================
Employee : {info['employee_name']}
Email    : {info['employee_email']}
Server   : {info['server_url']}

WINDOWS SETUP:
1. Install Python 3.11 from https://www.python.org/downloads/
   (Check "Add Python to PATH" during install)
2. Open this folder
3. Double-click: install_windows.bat
4. After install, double-click: start_windows.bat

MAC/LINUX SETUP:
1. Make sure Python 3.9+ is installed
2. Open Terminal in this folder
3. Run: bash install_mac.sh
4. Then: bash start_mac.sh

The agent runs silently in the background and monitors:
- Which applications you use
- Keyboard and mouse activity (counts only, no content)
- Idle time
- Active window titles

All data is sent securely to your company's PulseDesk server.
"""

    install_windows = """@echo off
echo Installing PulseDesk dependencies...
pip install -r requirements.txt
echo.
echo Installation complete! Run start_windows.bat to begin monitoring.
pause
"""

    install_mac = """#!/bin/bash
echo "Installing PulseDesk dependencies..."
pip3 install -r requirements.txt
echo "Installation complete! Run: bash start_mac.sh"
"""

    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("pulsedesk-agent/.env", env_content)
        zf.writestr("pulsedesk-agent/README.txt", readme)
        zf.writestr("pulsedesk-agent/start_windows.bat", windows_bat)
        zf.writestr("pulsedesk-agent/start_mac.sh", mac_sh)
        zf.writestr("pulsedesk-agent/install_windows.bat", install_windows)
        zf.writestr("pulsedesk-agent/install_mac.sh", install_mac)

        # Include core agent files
        agent_dir = Path(__file__).parent.parent.parent.parent.parent.parent / "agent"
        agent_files = [
            "agent.py", "requirements.txt",
            "core/config.py", "core/__init__.py",
            "capture/window_tracker.py", "capture/input_monitor.py", "capture/__init__.py",
            "sync/queue.py", "sync/client.py", "sync/__init__.py",
        ]
        for rel_path in agent_files:
            full_path = agent_dir / rel_path
            if full_path.exists():
                zf.write(full_path, f"pulsedesk-agent/{rel_path}")

    zip_buffer.seek(0)
    filename = f"pulsedesk-agent-{info['employee_name'].replace(' ', '_')}.zip"

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ─── Join page HTML ───────────────────────────────────────────────────────────

def _render_join_page() -> str:
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PulseDesk — Join</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #f5f5f4; min-height: 100vh;
    display: flex; align-items: center; justify-content: center; padding: 24px;
  }
  .card {
    background: #fff; border-radius: 16px; padding: 40px;
    box-shadow: 0 2px 12px rgba(0,0,0,0.08); width: 100%; max-width: 440px;
  }
  .logo { display: flex; align-items: center; gap: 10px; margin-bottom: 32px; justify-content: center; }
  .logo-icon {
    width: 36px; height: 36px; background: #2563eb; border-radius: 10px;
    display: flex; align-items: center; justify-content: center; color: #fff; font-size: 18px;
  }
  .logo-text { font-size: 20px; font-weight: 700; color: #1a1a18; letter-spacing: -0.02em; }
  h1 { font-size: 22px; font-weight: 600; color: #1a1a18; margin-bottom: 6px; }
  p { font-size: 14px; color: #72726a; line-height: 1.5; margin-bottom: 28px; }
  label { font-size: 12px; font-weight: 500; color: #52524e; display: block; margin-bottom: 6px; }
  input {
    width: 100%; padding: 12px 14px; font-size: 24px; font-weight: 600;
    letter-spacing: 0.2em; text-align: center; text-transform: uppercase;
    border: 1.5px solid #d1d0c8; border-radius: 10px; outline: none;
    transition: border-color 0.15s; font-family: monospace;
    color: #1a1a18; background: #fafaf9;
  }
  input:focus { border-color: #2563eb; background: #fff; }
  input::placeholder { color: #c8c7bf; letter-spacing: 0.1em; font-size: 20px; }
  .btn {
    width: 100%; padding: 14px; font-size: 15px; font-weight: 600;
    background: #2563eb; color: #fff; border: none; border-radius: 10px;
    cursor: pointer; margin-top: 16px; transition: background 0.15s;
  }
  .btn:hover { background: #1d4ed8; }
  .btn:disabled { opacity: 0.6; cursor: not-allowed; }
  .error {
    background: #fef2f2; color: #dc2626; padding: 10px 14px;
    border-radius: 8px; font-size: 13px; margin-top: 12px;
  }
  .success { display: none; }
  .success.visible { display: block; }
  .success-card {
    background: #f0fdf4; border: 1.5px solid #16a34a;
    border-radius: 12px; padding: 24px; text-align: center; margin-top: 16px;
  }
  .success-name { font-size: 18px; font-weight: 600; color: #15803d; margin-bottom: 4px; }
  .success-sub { font-size: 13px; color: #166534; margin-bottom: 20px; }
  .download-btn {
    display: inline-flex; align-items: center; gap: 8px;
    background: #16a34a; color: #fff; padding: 12px 24px;
    border-radius: 10px; font-size: 14px; font-weight: 600;
    text-decoration: none; transition: background 0.15s;
  }
  .download-btn:hover { background: #15803d; }
  .steps { margin-top: 24px; text-align: left; }
  .step { display: flex; gap: 12px; margin-bottom: 12px; align-items: flex-start; }
  .step-num {
    width: 24px; height: 24px; background: #eff6ff; color: #1d4ed8;
    border-radius: 50%; display: flex; align-items: center; justify-content: center;
    font-size: 12px; font-weight: 600; flex-shrink: 0; margin-top: 1px;
  }
  .step-text { font-size: 13px; color: #374151; line-height: 1.5; }
  .step-text strong { color: #111827; }
  .footer { text-align: center; margin-top: 24px; font-size: 12px; color: #a8a8a0; }
</style>
</head>
<body>
<div class="card">
  <div class="logo">
    <div class="logo-icon">⚡</div>
    <div class="logo-text">PulseDesk</div>
  </div>

  <div id="step1">
    <h1>Join your team</h1>
    <p>Enter the 6-character code your IT administrator sent you to set up monitoring on this device.</p>

    <label for="code">Your join code</label>
    <input type="text" id="code" maxlength="6" placeholder="ABC123"
      oninput="this.value = this.value.toUpperCase().replace(/[^A-Z0-9]/g,'')"
      onkeydown="if(event.key==='Enter') verify()">

    <div id="error" class="error" style="display:none"></div>

    <button class="btn" id="verifyBtn" onclick="verify()">
      Continue →
    </button>
  </div>

  <div id="step2" class="success">
    <div class="success-card">
      <div style="font-size:32px;margin-bottom:8px">✓</div>
      <div class="success-name" id="empName"></div>
      <div class="success-sub">Your device is enrolled and approved.</div>
      <a id="downloadBtn" class="download-btn" href="#">
        ⬇ Download monitoring agent
      </a>
    </div>

    <div class="steps">
      <div class="step">
        <div class="step-num">1</div>
        <div class="step-text"><strong>Download</strong> the ZIP file above</div>
      </div>
      <div class="step">
        <div class="step-num">2</div>
        <div class="step-text"><strong>Extract</strong> the ZIP to any folder (e.g. Desktop)</div>
      </div>
      <div class="step">
        <div class="step-num">3</div>
        <div class="step-text">
          <strong>Windows:</strong> Double-click <code>install_windows.bat</code> once, then <code>start_windows.bat</code><br>
          <strong>Mac:</strong> Open Terminal, run <code>bash install_mac.sh</code> then <code>bash start_mac.sh</code>
        </div>
      </div>
      <div class="step">
        <div class="step-num">4</div>
        <div class="step-text"><strong>Done!</strong> Monitoring will start automatically. Your admin can see you're online.</div>
      </div>
    </div>
  </div>

  <div class="footer">PulseDesk Employee Monitoring System</div>
</div>

<script>
async function verify() {
  const code = document.getElementById('code').value.trim();
  const btn = document.getElementById('verifyBtn');
  const errEl = document.getElementById('error');

  if (code.length < 6) {
    showError('Please enter the full 6-character code.');
    return;
  }

  btn.disabled = true;
  btn.textContent = 'Verifying...';
  errEl.style.display = 'none';

  try {
    const resp = await fetch('/join/verify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code }),
    });

    const data = await resp.json();

    if (!resp.ok) {
      showError(data.detail || 'Invalid code. Please check and try again.');
      btn.disabled = false;
      btn.textContent = 'Continue →';
      return;
    }

    // Show success
    document.getElementById('step1').style.display = 'none';
    document.getElementById('empName').textContent = 'Welcome, ' + data.employee_name + '!';
    document.getElementById('downloadBtn').href = data.download_url;
    document.getElementById('step2').classList.add('visible');

  } catch (e) {
    showError('Connection failed. Make sure the server is running.');
    btn.disabled = false;
    btn.textContent = 'Continue →';
  }
}

function showError(msg) {
  const el = document.getElementById('error');
  el.textContent = msg;
  el.style.display = 'block';
}
</script>
</body>
</html>"""
