"""add_break_alert_settings

Revision ID: 19b16f196448
Revises: 8890d5e0633d
Create Date: 2026-05-27 23:41:47.258495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b16f196448'
down_revision: Union[str, None] = '8890d5e0633d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_settings', sa.Column('break_alert_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('attendance_settings', sa.Column('break_alert_grace_minutes', sa.Integer(), nullable=False, server_default='5'))
    
    # Add enum value for excessive_break in PostgreSQL
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE anomalytype ADD VALUE 'excessive_break'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_settings', 'break_alert_grace_minutes')
    op.drop_column('attendance_settings', 'break_alert_enabled')
    # ### end Alembic commands ###
