"""add_anomaly_settings_columns

Revision ID: 5c69bac3ee9e
Revises: 7d97849f2493
Create Date: 2026-04-14 18:55:34.417617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c69bac3ee9e'
down_revision: Union[str, None] = '7d97849f2493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('excessive_idle_threshold_minutes', sa.Integer(), nullable=False))
    op.add_column('system_settings', sa.Column('distraction_threshold_minutes', sa.Integer(), nullable=False))
    op.add_column('system_settings', sa.Column('after_hours_min_active_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'after_hours_min_active_minutes')
    op.drop_column('system_settings', 'distraction_threshold_minutes')
    op.drop_column('system_settings', 'excessive_idle_threshold_minutes')
    # ### end Alembic commands ###
