"""Add missing features

Revision ID: 7d97849f2493
Revises: 
Create Date: 2026-04-14 02:04:27.186115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d97849f2493'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshot_policies', sa.Column('retention_days', sa.Integer(), nullable=False, server_default='7'))
    op.add_column('screenshot_policies', sa.Column('allowed_viewer_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshot_policies', 'allowed_viewer_roles')
    op.drop_column('screenshot_policies', 'retention_days')
    # ### end Alembic commands ###
