"""add_attendance_and_consent

Revision ID: 8890d5e0633d
Revises: ac2255182ab8
Create Date: 2026-05-27 20:56:38.756820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8890d5e0633d'
down_revision: Union[str, None] = 'ac2255182ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('employee', 'student', 'both', name='attendancemode'), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('work_start_time', sa.String(length=5), nullable=False),
    sa.Column('work_end_time', sa.String(length=5), nullable=False),
    sa.Column('lunch_break_enabled', sa.Boolean(), nullable=False),
    sa.Column('lunch_break_start_time', sa.String(length=5), nullable=False),
    sa.Column('lunch_break_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_deduct_lunch', sa.Boolean(), nullable=False),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('early_checkout_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('half_day_threshold_hours', sa.Float(), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('overtime_after_hours', sa.Float(), nullable=False),
    sa.Column('require_location_for_checkout', sa.Boolean(), nullable=False),
    sa.Column('allow_remote_checkin', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_latitude', sa.Float(), nullable=True),
    sa.Column('check_in_longitude', sa.Float(), nullable=True),
    sa.Column('check_out_latitude', sa.Float(), nullable=True),
    sa.Column('check_out_longitude', sa.Float(), nullable=True),
    sa.Column('check_in_location_id', sa.UUID(), nullable=True),
    sa.Column('check_out_location_id', sa.UUID(), nullable=True),
    sa.Column('check_in_within_geofence', sa.Boolean(), nullable=False),
    sa.Column('check_out_within_geofence', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('present', 'late', 'half_day', 'absent', 'on_leave', 'holiday', name='attendancestatus'), nullable=False),
    sa.Column('total_work_seconds', sa.Integer(), nullable=False),
    sa.Column('effective_work_seconds', sa.Integer(), nullable=False),
    sa.Column('overtime_seconds', sa.Integer(), nullable=False),
    sa.Column('lunch_deducted_seconds', sa.Integer(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_in_location_id'], ['attendance_locations.id'], ),
    sa.ForeignKeyConstraint(['check_out_location_id'], ['attendance_locations.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_employee_date')
    )
    op.create_index('ix_attendance_date_status', 'attendance_records', ['date', 'status'], unique=False)
    op.create_index('ix_attendance_employee_date', 'attendance_records', ['employee_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('lunch_break_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('auto_deducted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lunch_break_logs_attendance_record_id'), 'lunch_break_logs', ['attendance_record_id'], unique=False)
    op.add_column('blocked_site_rules', sa.Column('reason', sa.String(length=500), nullable=False, server_default='No reason'))
    op.add_column('blocked_site_rules', sa.Column('category', sa.String(length=50), nullable=False, server_default='custom'))
    op.add_column('blocked_site_rules', sa.Column('severity', sa.String(length=20), nullable=False, server_default='info'))
    op.add_column('blocked_site_rules', sa.Column('applies_to_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('blocked_site_rules', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('blocked_site_rules', sa.Column('employee_id', sa.UUID(), nullable=True))
    op.add_column('blocked_site_rules', sa.Column('violation_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('blocked_site_rules', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_lunch_break_logs_employee_id'), 'lunch_break_logs', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'blocked_site_rules', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'blocked_site_rules', 'departments', ['department_id'], ['id'])
    op.add_column('devices', sa.Column('monitoring_consent_given', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('employees', sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('consent_revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'consent_revoked_at')
    op.drop_column('employees', 'consent_given_at')
    op.drop_column('devices', 'monitoring_consent_given')
    op.drop_constraint(None, 'blocked_site_rules', type_='foreignkey')
    op.drop_constraint(None, 'blocked_site_rules', type_='foreignkey')
    op.alter_column('blocked_site_rules', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('blocked_site_rules', 'violation_count')
    op.drop_column('blocked_site_rules', 'employee_id')
    op.drop_column('blocked_site_rules', 'department_id')
    op.drop_column('blocked_site_rules', 'applies_to_all')
    op.drop_column('blocked_site_rules', 'severity')
    op.drop_column('blocked_site_rules', 'category')
    op.drop_column('blocked_site_rules', 'reason')
    op.drop_index(op.f('ix_lunch_break_logs_employee_id'), table_name='lunch_break_logs')
    op.drop_index(op.f('ix_lunch_break_logs_attendance_record_id'), table_name='lunch_break_logs')
    op.drop_table('lunch_break_logs')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_employee_date', table_name='attendance_records')
    op.drop_index('ix_attendance_date_status', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('attendance_settings')
    op.drop_table('attendance_locations')
    # ### end Alembic commands ###
