"""make_device_id_nullable

Revision ID: ac2255182ab8
Revises: 5c69bac3ee9e
Create Date: 2026-04-14 19:26:56.158234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2255182ab8'
down_revision: Union[str, None] = '5c69bac3ee9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_events', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('anomaly_logs', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('screenshots', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('work_sessions', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_sessions', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('screenshots', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('anomaly_logs', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_events', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
